#!/usr/bin/env bash
set -euo pipefail

# Deploy the Conflict & Duplication Detector Document Analysis API to Azure Container Instances (ACI).
#
# Prerequisites: az CLI, Docker, az login, and a populated repo-root .env file.
#
# Usage:
#   ./deployments/azure/create-aci.sh              # full deploy with Azure Files persistence
#   ./deployments/azure/create-aci.sh --skip-storage   # faster POC; data lost on restart
#   ./deployments/azure/create-aci.sh --redeploy       # rebuild image and recreate container

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_FILE="$SCRIPT_DIR/.aci-deploy.env"
ENV_FILE="$REPO_ROOT/.env"

SKIP_STORAGE=false
REDEPLOY=false

for arg in "$@"; do
  case "$arg" in
    --skip-storage) SKIP_STORAGE=true ;;
    --redeploy) REDEPLOY=true ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: '$1' is required but not installed." >&2
    exit 1
  fi
}

require_command az
require_command docker

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
else
  echo "Warning: $ENV_FILE not found. Set OPENAI_API_KEY (and other vars) in the environment." >&2
fi

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "Error: OPENAI_API_KEY is required. Add it to $ENV_FILE or export it." >&2
  exit 1
fi

# Deploy defaults (override via environment before running)
RG="${AZURE_RESOURCE_GROUP:-rg-document-analysis}"
LOCATION="${AZURE_LOCATION:-uksouth}"
CONTAINER_NAME="${ACI_CONTAINER_NAME:-aci-document-analysis}"
IMAGE_NAME="${ACI_IMAGE_NAME:-document-analysis}"
IMAGE_TAG="${ACI_IMAGE_TAG:-latest}"
CPU="${ACI_CPU:-2}"
MEMORY="${ACI_MEMORY_GB:-4}"
FILE_SHARE="${ACI_FILE_SHARE:-data}"

# App config from .env with sensible defaults
OpenAI__Provider="${OpenAI__Provider:-OpenAI}"
OpenAI__Model="${OpenAI__Model:-gpt-4o}"
OpenAI__EmbeddingModel="${OpenAI__EmbeddingModel:-text-embedding-3-small}"
OpenAI__AzureEndpoint="${OpenAI__AzureEndpoint:-}"
OpenAI__AzureApiVersion="${OpenAI__AzureApiVersion:-2024-02-01}"
OpenAI__ApiKeyHeader="${OpenAI__ApiKeyHeader:-}"
Auth__ApiKey="${Auth__ApiKey:-}"

if [[ -f "$STATE_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  if [[ "$REDEPLOY" == true && "${ACI_SKIP_STORAGE:-false}" == true ]]; then
    SKIP_STORAGE=true
  fi
fi

SUFFIX="${ACI_SUFFIX:-$(openssl rand -hex 3)}"
STORAGE="${ACI_STORAGE:-stdocumentanalysis${SUFFIX}}"
DNS_LABEL="${ACI_DNS_LABEL:-document-analysis-${SUFFIX}}"

resolve_acr_name() {
  if [[ -n "${ACI_ACR:-}" ]]; then
    echo "$ACI_ACR"
    return
  fi

  if az group show --name "$RG" >/dev/null 2>&1; then
    local existing_acr
    existing_acr="$(az acr list --resource-group "$RG" --query "[0].name" -o tsv 2>/dev/null || true)"
    if [[ -n "$existing_acr" ]]; then
      echo "$existing_acr"
      return
    fi
  fi

  echo "crdocumentanalysis${SUFFIX}"
}

ensure_acr() {
  if az acr show --name "$ACR" >/dev/null 2>&1; then
    echo "==> Using existing Azure Container Registry '$ACR'..."
    local admin_enabled
    admin_enabled="$(az acr show --name "$ACR" --query adminUserEnabled -o tsv)"
    if [[ "$admin_enabled" != "true" ]]; then
      echo "==> Enabling ACR admin user on '$ACR' (required for ACI image pull)..."
      az acr update --name "$ACR" --admin-enabled true --output none
    fi
    return
  fi

  echo "==> Creating Azure Container Registry '$ACR'..."
  az acr create --resource-group "$RG" --name "$ACR" --sku Basic --admin-enabled true --output none
}

save_state() {
  cat >"$STATE_FILE" <<EOF
# Generated by create-aci.sh — used by destroy-aci.sh
AZURE_RESOURCE_GROUP=$RG
AZURE_LOCATION=$LOCATION
ACI_CONTAINER_NAME=$CONTAINER_NAME
ACI_IMAGE_NAME=$IMAGE_NAME
ACI_IMAGE_TAG=$IMAGE_TAG
ACI_SUFFIX=$SUFFIX
ACI_ACR=$ACR
ACI_STORAGE=$STORAGE
ACI_DNS_LABEL=$DNS_LABEL
ACI_SKIP_STORAGE=$SKIP_STORAGE
EOF
}

echo "==> Checking Azure login..."
az account show >/dev/null

if [[ "$REDEPLOY" == true && ! -f "$STATE_FILE" ]]; then
  echo "Error: --redeploy requires an existing deployment ($STATE_FILE)." >&2
  exit 1
fi

if [[ "$REDEPLOY" == false && -f "$STATE_FILE" ]]; then
  echo "Existing deployment state found at $STATE_FILE"
  echo "Use --redeploy to rebuild the image and recreate the container, or destroy-aci.sh first."
  exit 1
fi

echo "==> Creating resource group '$RG' in $LOCATION..."
az group create --name "$RG" --location "$LOCATION" --output none

ACR="$(resolve_acr_name)"
ensure_acr

echo "==> Building and pushing container image..."
az acr login --name "$ACR"
FULL_IMAGE="$ACR.azurecr.io/$IMAGE_NAME:$IMAGE_TAG"
docker build -t "$FULL_IMAGE" "$REPO_ROOT"
docker push "$FULL_IMAGE"

ACR_PASSWORD="$(az acr credential show --name "$ACR" --query 'passwords[0].value' -o tsv)"

STORAGE_KEY=""
VOLUME_ARGS=()
if [[ "$SKIP_STORAGE" == false ]]; then
  if az storage account show --name "$STORAGE" --resource-group "$RG" >/dev/null 2>&1; then
    echo "==> Using existing storage account '$STORAGE'..."
  else
    echo "==> Creating storage account '$STORAGE' and file share '$FILE_SHARE'..."
    az storage account create \
      --name "$STORAGE" \
      --resource-group "$RG" \
      --location "$LOCATION" \
      --sku Standard_LRS \
      --output none
  fi

  STORAGE_KEY="$(az storage account keys list \
    --resource-group "$RG" \
    --account-name "$STORAGE" \
    --query '[0].value' -o tsv)"

  az storage share create \
    --name "$FILE_SHARE" \
    --account-name "$STORAGE" \
    --account-key "$STORAGE_KEY" \
    --output none 2>/dev/null || true

  VOLUME_ARGS=(
    --azure-file-volume-account-name "$STORAGE"
    --azure-file-volume-account-key "$STORAGE_KEY"
    --azure-file-volume-share-name "$FILE_SHARE"
    --azure-file-volume-mount-path /data
  )
else
  echo "==> Skipping Azure Files storage (--skip-storage). Data will not persist across restarts."
fi

if az container show --resource-group "$RG" --name "$CONTAINER_NAME" >/dev/null 2>&1; then
  echo "==> Removing existing container instance '$CONTAINER_NAME'..."
  az container delete --resource-group "$RG" --name "$CONTAINER_NAME" --yes --output none
fi

ENV_VARS=(
  "OpenAI__Provider=$OpenAI__Provider"
  "OpenAI__Model=$OpenAI__Model"
  "OpenAI__EmbeddingModel=$OpenAI__EmbeddingModel"
  "VectorStore__PersistPath=/data/vectors.json"
  "Storage__UploadsPath=/data/uploads"
)

if [[ -n "$OpenAI__AzureEndpoint" ]]; then
  ENV_VARS+=(
    "OpenAI__AzureEndpoint=$OpenAI__AzureEndpoint"
    "OpenAI__AzureApiVersion=$OpenAI__AzureApiVersion"
  )
fi

if [[ -n "$OpenAI__ApiKeyHeader" ]]; then
  ENV_VARS+=("OpenAI__ApiKeyHeader=$OpenAI__ApiKeyHeader")
fi

SECURE_ENV_VARS=("OPENAI_API_KEY=$OPENAI_API_KEY")
if [[ -n "$Auth__ApiKey" ]]; then
  SECURE_ENV_VARS+=("Auth__ApiKey=$Auth__ApiKey")
fi

echo "==> Creating container instance '$CONTAINER_NAME' (this may take a few minutes)..."
az container create \
  --resource-group "$RG" \
  --name "$CONTAINER_NAME" \
  --image "$FULL_IMAGE" \
  --os-type Linux \
  --registry-login-server "$ACR.azurecr.io" \
  --registry-username "$ACR" \
  --registry-password "$ACR_PASSWORD" \
  --dns-name-label "$DNS_LABEL" \
  --ports 8080 \
  --cpu "$CPU" \
  --memory "$MEMORY" \
  --environment-variables "${ENV_VARS[@]}" \
  --secure-environment-variables "${SECURE_ENV_VARS[@]}" \
  ${VOLUME_ARGS[@]+"${VOLUME_ARGS[@]}"} \
  --output none

save_state

FQDN="$(az container show \
  --resource-group "$RG" \
  --name "$CONTAINER_NAME" \
  --query ipAddress.fqdn -o tsv)"

echo ""
echo "Deployment complete."
echo ""
echo "  Resource group : $RG"
echo "  Container      : $CONTAINER_NAME"
echo "  Image          : $FULL_IMAGE"
echo "  FQDN           : $FQDN"
echo ""
echo "  Health : http://${FQDN}:8080/api/health"
echo "  Swagger: http://${FQDN}:8080/swagger"
if [[ -n "$Auth__ApiKey" ]]; then
  echo "  API key: set (send X-Api-Key header on protected routes)"
else
  echo "  API key: not set (inbound auth disabled)"
fi
echo ""
echo "  Logs   : az container logs --resource-group $RG --name $CONTAINER_NAME --follow"
echo "  Destroy: ./deployments/azure/destroy-aci.sh --yes"
echo ""
echo "State saved to $STATE_FILE"
